// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/handler/proto/service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	EmailVerified        bool     `protobuf:"varint,3,opt,name=EmailVerified,proto3" json:"EmailVerified,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	PhoneVerified        bool     `protobuf:"varint,5,opt,name=PhoneVerified,proto3" json:"PhoneVerified,omitempty"`
	Username             string   `protobuf:"bytes,6,opt,name=Username,proto3" json:"Username,omitempty"`
	Blocked              bool     `protobuf:"varint,7,opt,name=Blocked,proto3" json:"Blocked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc27373dff5c1c73, []int{0}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponse) GetEmailVerified() bool {
	if m != nil {
		return m.EmailVerified
	}
	return false
}

func (m *UserResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UserResponse) GetPhoneVerified() bool {
	if m != nil {
		return m.PhoneVerified
	}
	return false
}

func (m *UserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserResponse) GetBlocked() bool {
	if m != nil {
		return m.Blocked
	}
	return false
}

type GetProfileRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileRequest) Reset()         { *m = GetProfileRequest{} }
func (m *GetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetProfileRequest) ProtoMessage()    {}
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc27373dff5c1c73, []int{1}
}

func (m *GetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileRequest.Unmarshal(m, b)
}
func (m *GetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileRequest.Merge(m, src)
}
func (m *GetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetProfileRequest.Size(m)
}
func (m *GetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileRequest proto.InternalMessageInfo

func (m *GetProfileRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type SetProfileRequest struct {
	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	//
	Address1 string `protobuf:"bytes,2,opt,name=Address1,proto3" json:"Address1,omitempty"`
	Address2 string `protobuf:"bytes,3,opt,name=Address2,proto3" json:"Address2,omitempty"`
	City     string `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	State    string `protobuf:"bytes,5,opt,name=State,proto3" json:"State,omitempty"`
	Country  string `protobuf:"bytes,6,opt,name=Country,proto3" json:"Country,omitempty"`
	Zip      string `protobuf:"bytes,7,opt,name=Zip,proto3" json:"Zip,omitempty"`
	//
	PhotoURL  string `protobuf:"bytes,8,opt,name=PhotoURL,proto3" json:"PhotoURL,omitempty"`
	FirstName string `protobuf:"bytes,9,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName  string `protobuf:"bytes,10,opt,name=LastName,proto3" json:"LastName,omitempty"`
	BirthDate uint32 `protobuf:"varint,11,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	//
	Language             string   `protobuf:"bytes,12,opt,name=Language,proto3" json:"Language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetProfileRequest) Reset()         { *m = SetProfileRequest{} }
func (m *SetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*SetProfileRequest) ProtoMessage()    {}
func (*SetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc27373dff5c1c73, []int{2}
}

func (m *SetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetProfileRequest.Unmarshal(m, b)
}
func (m *SetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetProfileRequest.Marshal(b, m, deterministic)
}
func (m *SetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetProfileRequest.Merge(m, src)
}
func (m *SetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_SetProfileRequest.Size(m)
}
func (m *SetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetProfileRequest proto.InternalMessageInfo

func (m *SetProfileRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SetProfileRequest) GetAddress1() string {
	if m != nil {
		return m.Address1
	}
	return ""
}

func (m *SetProfileRequest) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *SetProfileRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *SetProfileRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *SetProfileRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *SetProfileRequest) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *SetProfileRequest) GetPhotoURL() string {
	if m != nil {
		return m.PhotoURL
	}
	return ""
}

func (m *SetProfileRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *SetProfileRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *SetProfileRequest) GetBirthDate() uint32 {
	if m != nil {
		return m.BirthDate
	}
	return 0
}

func (m *SetProfileRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type ProfileResponse struct {
	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	//
	Address1 string `protobuf:"bytes,2,opt,name=Address1,proto3" json:"Address1,omitempty"`
	Address2 string `protobuf:"bytes,3,opt,name=Address2,proto3" json:"Address2,omitempty"`
	City     string `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	State    string `protobuf:"bytes,5,opt,name=State,proto3" json:"State,omitempty"`
	Country  string `protobuf:"bytes,6,opt,name=Country,proto3" json:"Country,omitempty"`
	Zip      string `protobuf:"bytes,7,opt,name=Zip,proto3" json:"Zip,omitempty"`
	//
	PhotoURL  string `protobuf:"bytes,8,opt,name=PhotoURL,proto3" json:"PhotoURL,omitempty"`
	FirstName string `protobuf:"bytes,9,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName  string `protobuf:"bytes,10,opt,name=LastName,proto3" json:"LastName,omitempty"`
	BirthDate uint32 `protobuf:"varint,11,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	//
	Language             string   `protobuf:"bytes,12,opt,name=Language,proto3" json:"Language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileResponse) Reset()         { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()    {}
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc27373dff5c1c73, []int{3}
}

func (m *ProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileResponse.Unmarshal(m, b)
}
func (m *ProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileResponse.Marshal(b, m, deterministic)
}
func (m *ProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileResponse.Merge(m, src)
}
func (m *ProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileResponse.Size(m)
}
func (m *ProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileResponse proto.InternalMessageInfo

func (m *ProfileResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ProfileResponse) GetAddress1() string {
	if m != nil {
		return m.Address1
	}
	return ""
}

func (m *ProfileResponse) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *ProfileResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ProfileResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ProfileResponse) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *ProfileResponse) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *ProfileResponse) GetPhotoURL() string {
	if m != nil {
		return m.PhotoURL
	}
	return ""
}

func (m *ProfileResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ProfileResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *ProfileResponse) GetBirthDate() uint32 {
	if m != nil {
		return m.BirthDate
	}
	return 0
}

func (m *ProfileResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type GetSocialProfileRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSocialProfileRequest) Reset()         { *m = GetSocialProfileRequest{} }
func (m *GetSocialProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetSocialProfileRequest) ProtoMessage()    {}
func (*GetSocialProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc27373dff5c1c73, []int{4}
}

func (m *GetSocialProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSocialProfileRequest.Unmarshal(m, b)
}
func (m *GetSocialProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSocialProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetSocialProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSocialProfileRequest.Merge(m, src)
}
func (m *GetSocialProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetSocialProfileRequest.Size(m)
}
func (m *GetSocialProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSocialProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSocialProfileRequest proto.InternalMessageInfo

func (m *GetSocialProfileRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type SocialProfileResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Provider             string   `protobuf:"bytes,2,opt,name=Provider,proto3" json:"Provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialProfileResponse) Reset()         { *m = SocialProfileResponse{} }
func (m *SocialProfileResponse) String() string { return proto.CompactTextString(m) }
func (*SocialProfileResponse) ProtoMessage()    {}
func (*SocialProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc27373dff5c1c73, []int{5}
}

func (m *SocialProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialProfileResponse.Unmarshal(m, b)
}
func (m *SocialProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialProfileResponse.Marshal(b, m, deterministic)
}
func (m *SocialProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialProfileResponse.Merge(m, src)
}
func (m *SocialProfileResponse) XXX_Size() int {
	return xxx_messageInfo_SocialProfileResponse.Size(m)
}
func (m *SocialProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SocialProfileResponse proto.InternalMessageInfo

func (m *SocialProfileResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SocialProfileResponse) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

type SocialProfilesListResponse struct {
	SocialProfile        []*SocialProfileResponse `protobuf:"bytes,1,rep,name=SocialProfile,proto3" json:"SocialProfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SocialProfilesListResponse) Reset()         { *m = SocialProfilesListResponse{} }
func (m *SocialProfilesListResponse) String() string { return proto.CompactTextString(m) }
func (*SocialProfilesListResponse) ProtoMessage()    {}
func (*SocialProfilesListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc27373dff5c1c73, []int{6}
}

func (m *SocialProfilesListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialProfilesListResponse.Unmarshal(m, b)
}
func (m *SocialProfilesListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialProfilesListResponse.Marshal(b, m, deterministic)
}
func (m *SocialProfilesListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialProfilesListResponse.Merge(m, src)
}
func (m *SocialProfilesListResponse) XXX_Size() int {
	return xxx_messageInfo_SocialProfilesListResponse.Size(m)
}
func (m *SocialProfilesListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialProfilesListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SocialProfilesListResponse proto.InternalMessageInfo

func (m *SocialProfilesListResponse) GetSocialProfile() []*SocialProfileResponse {
	if m != nil {
		return m.SocialProfile
	}
	return nil
}

type SetPasswordRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PasswordOld          string   `protobuf:"bytes,2,opt,name=PasswordOld,proto3" json:"PasswordOld,omitempty"`
	PasswordNew          string   `protobuf:"bytes,3,opt,name=PasswordNew,proto3" json:"PasswordNew,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordRequest) Reset()         { *m = SetPasswordRequest{} }
func (m *SetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*SetPasswordRequest) ProtoMessage()    {}
func (*SetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc27373dff5c1c73, []int{7}
}

func (m *SetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordRequest.Unmarshal(m, b)
}
func (m *SetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *SetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordRequest.Merge(m, src)
}
func (m *SetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_SetPasswordRequest.Size(m)
}
func (m *SetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordRequest proto.InternalMessageInfo

func (m *SetPasswordRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SetPasswordRequest) GetPasswordOld() string {
	if m != nil {
		return m.PasswordOld
	}
	return ""
}

func (m *SetPasswordRequest) GetPasswordNew() string {
	if m != nil {
		return m.PasswordNew
	}
	return ""
}

type SetPasswordResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordResponse) Reset()         { *m = SetPasswordResponse{} }
func (m *SetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*SetPasswordResponse) ProtoMessage()    {}
func (*SetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc27373dff5c1c73, []int{8}
}

func (m *SetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordResponse.Unmarshal(m, b)
}
func (m *SetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *SetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordResponse.Merge(m, src)
}
func (m *SetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_SetPasswordResponse.Size(m)
}
func (m *SetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordResponse proto.InternalMessageInfo

func (m *SetPasswordResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SetPasswordResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*UserResponse)(nil), "proto.UserResponse")
	proto.RegisterType((*GetProfileRequest)(nil), "proto.GetProfileRequest")
	proto.RegisterType((*SetProfileRequest)(nil), "proto.SetProfileRequest")
	proto.RegisterType((*ProfileResponse)(nil), "proto.ProfileResponse")
	proto.RegisterType((*GetSocialProfileRequest)(nil), "proto.GetSocialProfileRequest")
	proto.RegisterType((*SocialProfileResponse)(nil), "proto.SocialProfileResponse")
	proto.RegisterType((*SocialProfilesListResponse)(nil), "proto.SocialProfilesListResponse")
	proto.RegisterType((*SetPasswordRequest)(nil), "proto.SetPasswordRequest")
	proto.RegisterType((*SetPasswordResponse)(nil), "proto.SetPasswordResponse")
}

func init() {
	proto.RegisterFile("internal/handler/proto/service.proto", fileDescriptor_fc27373dff5c1c73)
}

var fileDescriptor_fc27373dff5c1c73 = []byte{
	// 538 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x54, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xfe, 0x9d, 0x34, 0xa7, 0x49, 0xf3, 0x43, 0x17, 0x28, 0xab, 0xa8, 0x17, 0x91, 0xd5, 0x8b,
	0x48, 0x48, 0x8d, 0x1a, 0x5e, 0x00, 0xd2, 0x40, 0x54, 0x11, 0x95, 0xc8, 0x56, 0xb9, 0xe0, 0x0a,
	0x93, 0x9d, 0x36, 0x2b, 0x5c, 0x6f, 0xd8, 0xdd, 0xb4, 0xea, 0x43, 0xf0, 0x5c, 0x08, 0x89, 0x87,
	0x42, 0x7b, 0xb0, 0x13, 0xa7, 0xa0, 0x56, 0x5c, 0x73, 0x95, 0xf9, 0x66, 0xe6, 0x9b, 0xc3, 0xe7,
	0xcd, 0xc0, 0x21, 0xcf, 0x34, 0xca, 0x2c, 0x49, 0x07, 0x8b, 0x24, 0x63, 0x29, 0xca, 0xc1, 0x52,
	0x0a, 0x2d, 0x06, 0x0a, 0xe5, 0x35, 0x9f, 0xe3, 0x91, 0x45, 0xa4, 0x66, 0x7f, 0xc2, 0x9f, 0x01,
	0xec, 0x9e, 0x2b, 0x94, 0x11, 0xaa, 0xa5, 0xc8, 0x14, 0x92, 0xff, 0xa1, 0x72, 0x3a, 0xa6, 0x41,
	0x2f, 0xe8, 0xb7, 0xa2, 0xca, 0xe9, 0x98, 0x3c, 0x85, 0xda, 0x9b, 0xab, 0x84, 0xa7, 0xb4, 0x62,
	0x5d, 0x0e, 0x90, 0x43, 0xe8, 0x58, 0xe3, 0x03, 0x4a, 0x7e, 0xc1, 0x91, 0xd1, 0x6a, 0x2f, 0xe8,
	0x37, 0xa3, 0xb2, 0xd3, 0x70, 0x67, 0x0b, 0x91, 0x21, 0xdd, 0x71, 0x5c, 0x0b, 0x0c, 0xd7, 0x1a,
	0x05, 0xb7, 0xe6, 0xb8, 0x25, 0x27, 0xe9, 0x42, 0xd3, 0xcc, 0x95, 0x25, 0x57, 0x48, 0xeb, 0x96,
	0x5e, 0x60, 0x42, 0xa1, 0x31, 0x4a, 0xc5, 0xfc, 0x0b, 0x32, 0xda, 0xb0, 0xdc, 0x1c, 0x86, 0x2f,
	0x60, 0x6f, 0x82, 0x7a, 0x26, 0xc5, 0x05, 0x4f, 0x31, 0xc2, 0xaf, 0x2b, 0x54, 0x9a, 0xec, 0x43,
	0xdd, 0x50, 0x8b, 0xb5, 0x3c, 0x0a, 0x7f, 0x54, 0x60, 0x2f, 0x7e, 0x68, 0xb6, 0x19, 0xe8, 0x35,
	0x63, 0x12, 0x95, 0x3a, 0xf6, 0x5a, 0x14, 0x78, 0x23, 0x36, 0xb4, 0x4a, 0xac, 0x63, 0x43, 0x42,
	0x60, 0xe7, 0x84, 0xeb, 0x5b, 0xaf, 0x81, 0xb5, 0x8d, 0x30, 0xb1, 0x4e, 0x34, 0xda, 0xd5, 0x5b,
	0x91, 0x03, 0x66, 0xad, 0x13, 0xb1, 0xca, 0xb4, 0xbc, 0xf5, 0x1b, 0xe7, 0x90, 0x3c, 0x86, 0xea,
	0x47, 0xbe, 0xb4, 0xcb, 0xb6, 0x22, 0x63, 0x9a, 0x8e, 0xb3, 0x85, 0xd0, 0xe2, 0x3c, 0x9a, 0xd2,
	0xa6, 0xeb, 0x98, 0x63, 0x72, 0x00, 0xad, 0xb7, 0x5c, 0x2a, 0x7d, 0x66, 0xb4, 0x6b, 0xd9, 0xe0,
	0xda, 0x61, 0x98, 0xd3, 0xc4, 0x07, 0xc1, 0x31, 0x73, 0x6c, 0x98, 0x23, 0x2e, 0xf5, 0x62, 0x6c,
	0x66, 0x6b, 0xf7, 0x82, 0x7e, 0x27, 0x5a, 0x3b, 0x1c, 0x33, 0xbb, 0x5c, 0x25, 0x97, 0x48, 0x77,
	0x73, 0xa6, 0xc3, 0xe1, 0xf7, 0x0a, 0x3c, 0x2a, 0x84, 0xf4, 0x4f, 0xe9, 0x9f, 0x92, 0x7f, 0xa3,
	0xe4, 0x31, 0x3c, 0x9f, 0xa0, 0x8e, 0xc5, 0x9c, 0x27, 0xe9, 0x1f, 0x9e, 0x26, 0x2b, 0x09, 0xca,
	0xc2, 0x77, 0xf0, 0x6c, 0x2b, 0x7f, 0xeb, 0x0b, 0x6c, 0x11, 0xec, 0xce, 0x52, 0x5c, 0x73, 0x86,
	0x32, 0xff, 0x02, 0x39, 0x0e, 0x3f, 0x41, 0xb7, 0x54, 0x4c, 0x4d, 0xb9, 0xd2, 0x45, 0xc5, 0x11,
	0x74, 0x4a, 0x51, 0x1a, 0xf4, 0xaa, 0xfd, 0xf6, 0xf0, 0xc0, 0x5d, 0x95, 0xa3, 0xdf, 0x8e, 0x11,
	0x95, 0x29, 0xe1, 0x12, 0x88, 0xf9, 0xdb, 0x25, 0x4a, 0xdd, 0x08, 0xc9, 0xee, 0x59, 0x8e, 0xf4,
	0xa0, 0x9d, 0xa7, 0xbe, 0x4f, 0x99, 0x1f, 0x77, 0xd3, 0xb5, 0x99, 0x71, 0x86, 0x37, 0xfe, 0xd9,
	0x6c, 0xba, 0xc2, 0x09, 0x3c, 0x29, 0x75, 0xbc, 0x47, 0x1e, 0x0a, 0x8d, 0x78, 0x35, 0x9f, 0xa3,
	0x52, 0xb6, 0x5d, 0x33, 0xca, 0xe1, 0xf0, 0x5b, 0x00, 0x8d, 0xd8, 0xdd, 0x51, 0xf2, 0x0a, 0x60,
	0x7d, 0x6b, 0x08, 0xf5, 0x0a, 0xdc, 0x39, 0x3f, 0xdd, 0x7d, 0x1f, 0xd9, 0x52, 0x25, 0xfc, 0xcf,
	0x54, 0x88, 0xef, 0x56, 0x88, 0x1f, 0x5e, 0xe1, 0x73, 0xdd, 0x06, 0x5e, 0xfe, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0x5a, 0x19, 0xb9, 0xb2, 0xf4, 0x05, 0x00, 0x00,
}
