// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/grpc/proto/service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetProfileRequest struct {
	AppID                string   `protobuf:"bytes,1,opt,name=AppID,proto3" json:"AppID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileRequest) Reset()         { *m = GetProfileRequest{} }
func (m *GetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetProfileRequest) ProtoMessage()    {}
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c745b77facf9f532, []int{0}
}

func (m *GetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileRequest.Unmarshal(m, b)
}
func (m *GetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileRequest.Merge(m, src)
}
func (m *GetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetProfileRequest.Size(m)
}
func (m *GetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileRequest proto.InternalMessageInfo

func (m *GetProfileRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *GetProfileRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type SetProfileRequest struct {
	AppID  string `protobuf:"bytes,1,opt,name=AppID,proto3" json:"AppID,omitempty"`
	UserID string `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	//
	Address1 string `protobuf:"bytes,3,opt,name=Address1,proto3" json:"Address1,omitempty"`
	Address2 string `protobuf:"bytes,4,opt,name=Address2,proto3" json:"Address2,omitempty"`
	City     string `protobuf:"bytes,5,opt,name=City,proto3" json:"City,omitempty"`
	State    string `protobuf:"bytes,6,opt,name=State,proto3" json:"State,omitempty"`
	Country  string `protobuf:"bytes,7,opt,name=Country,proto3" json:"Country,omitempty"`
	Zip      string `protobuf:"bytes,8,opt,name=Zip,proto3" json:"Zip,omitempty"`
	//
	PhotoURL  string               `protobuf:"bytes,9,opt,name=PhotoURL,proto3" json:"PhotoURL,omitempty"`
	FirstName string               `protobuf:"bytes,10,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName  string               `protobuf:"bytes,11,opt,name=LastName,proto3" json:"LastName,omitempty"`
	BirthDate *timestamp.Timestamp `protobuf:"bytes,12,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	//
	Language             string   `protobuf:"bytes,13,opt,name=Language,proto3" json:"Language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetProfileRequest) Reset()         { *m = SetProfileRequest{} }
func (m *SetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*SetProfileRequest) ProtoMessage()    {}
func (*SetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c745b77facf9f532, []int{1}
}

func (m *SetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetProfileRequest.Unmarshal(m, b)
}
func (m *SetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetProfileRequest.Marshal(b, m, deterministic)
}
func (m *SetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetProfileRequest.Merge(m, src)
}
func (m *SetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_SetProfileRequest.Size(m)
}
func (m *SetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetProfileRequest proto.InternalMessageInfo

func (m *SetProfileRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *SetProfileRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SetProfileRequest) GetAddress1() string {
	if m != nil {
		return m.Address1
	}
	return ""
}

func (m *SetProfileRequest) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *SetProfileRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *SetProfileRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *SetProfileRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *SetProfileRequest) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *SetProfileRequest) GetPhotoURL() string {
	if m != nil {
		return m.PhotoURL
	}
	return ""
}

func (m *SetProfileRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *SetProfileRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *SetProfileRequest) GetBirthDate() *timestamp.Timestamp {
	if m != nil {
		return m.BirthDate
	}
	return nil
}

func (m *SetProfileRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type ProfileResponse struct {
	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	//
	Email    string `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
	//
	Phone string `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	//
	Address1 string `protobuf:"bytes,5,opt,name=Address1,proto3" json:"Address1,omitempty"`
	Address2 string `protobuf:"bytes,6,opt,name=Address2,proto3" json:"Address2,omitempty"`
	City     string `protobuf:"bytes,7,opt,name=City,proto3" json:"City,omitempty"`
	State    string `protobuf:"bytes,8,opt,name=State,proto3" json:"State,omitempty"`
	Country  string `protobuf:"bytes,9,opt,name=Country,proto3" json:"Country,omitempty"`
	Zip      string `protobuf:"bytes,10,opt,name=Zip,proto3" json:"Zip,omitempty"`
	//
	PhotoURL  string               `protobuf:"bytes,11,opt,name=PhotoURL,proto3" json:"PhotoURL,omitempty"`
	FirstName string               `protobuf:"bytes,12,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName  string               `protobuf:"bytes,13,opt,name=LastName,proto3" json:"LastName,omitempty"`
	BirthDate *timestamp.Timestamp `protobuf:"bytes,14,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	//
	Language             string   `protobuf:"bytes,15,opt,name=Language,proto3" json:"Language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileResponse) Reset()         { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()    {}
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c745b77facf9f532, []int{2}
}

func (m *ProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileResponse.Unmarshal(m, b)
}
func (m *ProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileResponse.Marshal(b, m, deterministic)
}
func (m *ProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileResponse.Merge(m, src)
}
func (m *ProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileResponse.Size(m)
}
func (m *ProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileResponse proto.InternalMessageInfo

func (m *ProfileResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ProfileResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ProfileResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ProfileResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ProfileResponse) GetAddress1() string {
	if m != nil {
		return m.Address1
	}
	return ""
}

func (m *ProfileResponse) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *ProfileResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ProfileResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ProfileResponse) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *ProfileResponse) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *ProfileResponse) GetPhotoURL() string {
	if m != nil {
		return m.PhotoURL
	}
	return ""
}

func (m *ProfileResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ProfileResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *ProfileResponse) GetBirthDate() *timestamp.Timestamp {
	if m != nil {
		return m.BirthDate
	}
	return nil
}

func (m *ProfileResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type SetPasswordRequest struct {
	AppID                string   `protobuf:"bytes,1,opt,name=appID,proto3" json:"appID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	PasswordOld          string   `protobuf:"bytes,3,opt,name=passwordOld,proto3" json:"passwordOld,omitempty"`
	PasswordNew          string   `protobuf:"bytes,4,opt,name=passwordNew,proto3" json:"passwordNew,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordRequest) Reset()         { *m = SetPasswordRequest{} }
func (m *SetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*SetPasswordRequest) ProtoMessage()    {}
func (*SetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c745b77facf9f532, []int{3}
}

func (m *SetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordRequest.Unmarshal(m, b)
}
func (m *SetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *SetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordRequest.Merge(m, src)
}
func (m *SetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_SetPasswordRequest.Size(m)
}
func (m *SetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordRequest proto.InternalMessageInfo

func (m *SetPasswordRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *SetPasswordRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SetPasswordRequest) GetPasswordOld() string {
	if m != nil {
		return m.PasswordOld
	}
	return ""
}

func (m *SetPasswordRequest) GetPasswordNew() string {
	if m != nil {
		return m.PasswordNew
	}
	return ""
}

type SetPasswordResponse struct {
	AppID                string   `protobuf:"bytes,1,opt,name=appID,proto3" json:"appID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	Success              bool     `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordResponse) Reset()         { *m = SetPasswordResponse{} }
func (m *SetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*SetPasswordResponse) ProtoMessage()    {}
func (*SetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c745b77facf9f532, []int{4}
}

func (m *SetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordResponse.Unmarshal(m, b)
}
func (m *SetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *SetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordResponse.Merge(m, src)
}
func (m *SetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_SetPasswordResponse.Size(m)
}
func (m *SetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordResponse proto.InternalMessageInfo

func (m *SetPasswordResponse) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *SetPasswordResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SetPasswordResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetUserSocialIdentitiesRequest struct {
	AppID                string   `protobuf:"bytes,1,opt,name=appID,proto3" json:"appID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserSocialIdentitiesRequest) Reset()         { *m = GetUserSocialIdentitiesRequest{} }
func (m *GetUserSocialIdentitiesRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserSocialIdentitiesRequest) ProtoMessage()    {}
func (*GetUserSocialIdentitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c745b77facf9f532, []int{5}
}

func (m *GetUserSocialIdentitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserSocialIdentitiesRequest.Unmarshal(m, b)
}
func (m *GetUserSocialIdentitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserSocialIdentitiesRequest.Marshal(b, m, deterministic)
}
func (m *GetUserSocialIdentitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserSocialIdentitiesRequest.Merge(m, src)
}
func (m *GetUserSocialIdentitiesRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserSocialIdentitiesRequest.Size(m)
}
func (m *GetUserSocialIdentitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserSocialIdentitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserSocialIdentitiesRequest proto.InternalMessageInfo

func (m *GetUserSocialIdentitiesRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *GetUserSocialIdentitiesRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UserIdentity struct {
	Provider             string   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ExternalID           string   `protobuf:"bytes,2,opt,name=externalID,proto3" json:"externalID,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserIdentity) Reset()         { *m = UserIdentity{} }
func (m *UserIdentity) String() string { return proto.CompactTextString(m) }
func (*UserIdentity) ProtoMessage()    {}
func (*UserIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_c745b77facf9f532, []int{6}
}

func (m *UserIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIdentity.Unmarshal(m, b)
}
func (m *UserIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIdentity.Marshal(b, m, deterministic)
}
func (m *UserIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIdentity.Merge(m, src)
}
func (m *UserIdentity) XXX_Size() int {
	return xxx_messageInfo_UserIdentity.Size(m)
}
func (m *UserIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_UserIdentity proto.InternalMessageInfo

func (m *UserIdentity) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *UserIdentity) GetExternalID() string {
	if m != nil {
		return m.ExternalID
	}
	return ""
}

func (m *UserIdentity) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserIdentity) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserIdentity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserSocialIdentitiesResponse struct {
	Identities           []*UserIdentity `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserSocialIdentitiesResponse) Reset()         { *m = UserSocialIdentitiesResponse{} }
func (m *UserSocialIdentitiesResponse) String() string { return proto.CompactTextString(m) }
func (*UserSocialIdentitiesResponse) ProtoMessage()    {}
func (*UserSocialIdentitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c745b77facf9f532, []int{7}
}

func (m *UserSocialIdentitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSocialIdentitiesResponse.Unmarshal(m, b)
}
func (m *UserSocialIdentitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSocialIdentitiesResponse.Marshal(b, m, deterministic)
}
func (m *UserSocialIdentitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSocialIdentitiesResponse.Merge(m, src)
}
func (m *UserSocialIdentitiesResponse) XXX_Size() int {
	return xxx_messageInfo_UserSocialIdentitiesResponse.Size(m)
}
func (m *UserSocialIdentitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSocialIdentitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserSocialIdentitiesResponse proto.InternalMessageInfo

func (m *UserSocialIdentitiesResponse) GetIdentities() []*UserIdentity {
	if m != nil {
		return m.Identities
	}
	return nil
}

func init() {
	proto.RegisterType((*GetProfileRequest)(nil), "proto.GetProfileRequest")
	proto.RegisterType((*SetProfileRequest)(nil), "proto.SetProfileRequest")
	proto.RegisterType((*ProfileResponse)(nil), "proto.ProfileResponse")
	proto.RegisterType((*SetPasswordRequest)(nil), "proto.SetPasswordRequest")
	proto.RegisterType((*SetPasswordResponse)(nil), "proto.SetPasswordResponse")
	proto.RegisterType((*GetUserSocialIdentitiesRequest)(nil), "proto.GetUserSocialIdentitiesRequest")
	proto.RegisterType((*UserIdentity)(nil), "proto.UserIdentity")
	proto.RegisterType((*UserSocialIdentitiesResponse)(nil), "proto.UserSocialIdentitiesResponse")
}

func init() {
	proto.RegisterFile("internal/grpc/proto/service.proto", fileDescriptor_c745b77facf9f532)
}

var fileDescriptor_c745b77facf9f532 = []byte{
	// 653 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x4e, 0xdb, 0x30,
	0x14, 0x26, 0x94, 0xfe, 0x9d, 0xc2, 0x18, 0x06, 0x31, 0x2f, 0x42, 0xac, 0xcb, 0x34, 0x89, 0xab,
	0x56, 0x2b, 0x37, 0xbb, 0x1c, 0x83, 0x81, 0x90, 0x10, 0x43, 0xcd, 0xb8, 0x99, 0xb4, 0x8b, 0xd0,
	0x9a, 0x62, 0x29, 0x8d, 0x33, 0xdb, 0x81, 0xf5, 0x05, 0x76, 0xbd, 0xf7, 0xd8, 0x3b, 0xec, 0xc5,
	0x76, 0x33, 0xf9, 0x27, 0xa9, 0x03, 0x6d, 0x25, 0xd8, 0x55, 0xf2, 0x9d, 0x63, 0x7f, 0xb6, 0xbf,
	0xef, 0x9c, 0x03, 0xaf, 0x69, 0x22, 0x09, 0x4f, 0xa2, 0xb8, 0x3b, 0xe2, 0xe9, 0xa0, 0x9b, 0x72,
	0x26, 0x59, 0x57, 0x10, 0x7e, 0x4b, 0x07, 0xa4, 0xa3, 0x11, 0xaa, 0xea, 0x8f, 0xff, 0x6a, 0xc4,
	0xd8, 0x28, 0x26, 0x66, 0xc9, 0x55, 0x76, 0xdd, 0x95, 0x74, 0x4c, 0x84, 0x8c, 0xc6, 0xa9, 0x59,
	0x17, 0x1c, 0xc0, 0xc6, 0x09, 0x91, 0x17, 0x9c, 0x5d, 0xd3, 0x98, 0xf4, 0xc9, 0xf7, 0x8c, 0x08,
	0x89, 0xb6, 0xa0, 0x7a, 0x90, 0xa6, 0xa7, 0x47, 0xd8, 0x6b, 0x7b, 0x7b, 0xcd, 0xbe, 0x01, 0x68,
	0x1b, 0x6a, 0x97, 0x82, 0xf0, 0xd3, 0x23, 0xbc, 0xac, 0xc3, 0x16, 0x05, 0x7f, 0x97, 0x61, 0x23,
	0xfc, 0x3f, 0x0e, 0xe4, 0x43, 0xe3, 0x60, 0x38, 0xe4, 0x44, 0x88, 0x77, 0xb8, 0xa2, 0x33, 0x05,
	0x76, 0x72, 0x3d, 0xbc, 0x52, 0xca, 0xf5, 0x10, 0x82, 0x95, 0x43, 0x2a, 0x27, 0xb8, 0xaa, 0xe3,
	0xfa, 0x5f, 0x9d, 0x1c, 0xca, 0x48, 0x12, 0x5c, 0x33, 0x27, 0x6b, 0x80, 0x30, 0xd4, 0x0f, 0x59,
	0x96, 0x48, 0x3e, 0xc1, 0x75, 0x1d, 0xcf, 0x21, 0x7a, 0x0e, 0x95, 0xaf, 0x34, 0xc5, 0x0d, 0x1d,
	0x55, 0xbf, 0xea, 0xc4, 0x8b, 0x1b, 0x26, 0xd9, 0x65, 0xff, 0x0c, 0x37, 0xcd, 0x89, 0x39, 0x46,
	0x3b, 0xd0, 0x3c, 0xa6, 0x5c, 0xc8, 0xf3, 0x68, 0x4c, 0x30, 0xe8, 0xe4, 0x34, 0xa0, 0x76, 0x9e,
	0x45, 0x36, 0xd9, 0x32, 0x3b, 0x73, 0x8c, 0xde, 0x43, 0xf3, 0x23, 0xe5, 0xf2, 0xe6, 0x48, 0xdd,
	0x6d, 0xb5, 0xed, 0xed, 0xb5, 0x7a, 0x7e, 0xc7, 0xf8, 0xd3, 0xc9, 0xfd, 0xe9, 0x7c, 0xc9, 0xfd,
	0xe9, 0x4f, 0x17, 0x1b, 0xd6, 0x64, 0x94, 0x45, 0x23, 0x82, 0xd7, 0x72, 0x56, 0x83, 0x83, 0xdf,
	0x15, 0x58, 0x2f, 0xa4, 0x17, 0x29, 0x4b, 0x04, 0x71, 0x54, 0xf6, 0x4a, 0x2a, 0x6f, 0x41, 0xf5,
	0xd3, 0x38, 0xa2, 0xb1, 0x15, 0xdf, 0x00, 0xc5, 0xae, 0xf2, 0x89, 0xba, 0xb3, 0xd5, 0x3e, 0xc7,
	0x6a, 0xc7, 0xc5, 0x0d, 0x4b, 0x88, 0x15, 0xde, 0x80, 0x92, 0x5b, 0xd5, 0x05, 0x6e, 0xd5, 0xe6,
	0xb8, 0x55, 0x9f, 0xe5, 0x56, 0x63, 0x8e, 0x5b, 0xcd, 0x99, 0x6e, 0xc1, 0x6c, 0xb7, 0x5a, 0x8b,
	0xdc, 0x5a, 0x5d, 0xe4, 0xd6, 0xda, 0x22, 0xb7, 0x9e, 0x3d, 0xd5, 0xad, 0xf5, 0x7b, 0x6e, 0xfd,
	0xf4, 0x00, 0xa9, 0x5e, 0x89, 0x84, 0xb8, 0x63, 0x7c, 0xe8, 0x34, 0x4b, 0xe4, 0x36, 0x4b, 0x94,
	0x37, 0x4b, 0x56, 0x6a, 0x16, 0x83, 0x50, 0x1b, 0x5a, 0xa9, 0x25, 0xf8, 0x1c, 0x0f, 0xad, 0x67,
	0x6e, 0xc8, 0x5d, 0x71, 0x4e, 0xee, 0xac, 0x79, 0x6e, 0x28, 0xf8, 0x06, 0x9b, 0xa5, 0x7b, 0xd8,
	0xca, 0x79, 0xdc, 0x45, 0x30, 0xd4, 0x45, 0x36, 0x18, 0x10, 0x21, 0xf4, 0x25, 0x1a, 0xfd, 0x1c,
	0x06, 0xe7, 0xb0, 0x7b, 0x42, 0xa4, 0x2a, 0xa3, 0x90, 0x0d, 0x68, 0x14, 0x9f, 0x0e, 0x49, 0x22,
	0xa9, 0xa4, 0x44, 0x3c, 0xe9, 0xc9, 0xc1, 0x2f, 0x0f, 0x56, 0x75, 0x11, 0x1b, 0x9e, 0x89, 0x12,
	0x39, 0xe5, 0xec, 0x96, 0x0e, 0x09, 0xb7, 0x0c, 0x05, 0x46, 0xbb, 0x00, 0xe4, 0x87, 0x19, 0x90,
	0x05, 0x91, 0x13, 0x51, 0x47, 0x13, 0xdd, 0x06, 0x46, 0x39, 0x03, 0x14, 0x63, 0x96, 0xb7, 0x81,
	0x1d, 0x33, 0x39, 0x56, 0x85, 0xab, 0xe3, 0x76, 0xcc, 0xa8, 0xff, 0x20, 0x84, 0x9d, 0xd9, 0xef,
	0xb3, 0x52, 0xee, 0x03, 0xd0, 0x22, 0x8a, 0xbd, 0x76, 0x65, 0xaf, 0xd5, 0xdb, 0x34, 0xa5, 0xd3,
	0x71, 0x9f, 0xd2, 0x77, 0x96, 0xf5, 0xfe, 0x2c, 0x43, 0x3d, 0x34, 0x83, 0x1c, 0x7d, 0x00, 0x98,
	0x8e, 0x66, 0x84, 0xed, 0xd6, 0x07, 0xd3, 0xda, 0xdf, 0xb6, 0x99, 0x7b, 0x53, 0x20, 0x58, 0x52,
	0x0c, 0xe1, 0x43, 0x86, 0xf0, 0x11, 0x0c, 0xc7, 0xd0, 0x72, 0xca, 0x04, 0xbd, 0x74, 0x28, 0xca,
	0x25, 0xec, 0xfb, 0xb3, 0x52, 0x05, 0xcf, 0x08, 0x5e, 0xcc, 0xa9, 0x07, 0xf4, 0x76, 0xfa, 0xb0,
	0x05, 0xf5, 0xe2, 0xbf, 0x71, 0xa4, 0x9b, 0xa7, 0x79, 0xb0, 0x74, 0x55, 0xd3, 0xab, 0xf6, 0xff,
	0x05, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x02, 0x85, 0x16, 0x23, 0x07, 0x00, 0x00,
}
