// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/grpc/proto/service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetProfileRequest struct {
	AppID                string   `protobuf:"bytes,1,opt,name=AppID,proto3" json:"AppID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileRequest) Reset()         { *m = GetProfileRequest{} }
func (m *GetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetProfileRequest) ProtoMessage()    {}
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c745b77facf9f532, []int{0}
}

func (m *GetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileRequest.Unmarshal(m, b)
}
func (m *GetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileRequest.Merge(m, src)
}
func (m *GetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetProfileRequest.Size(m)
}
func (m *GetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileRequest proto.InternalMessageInfo

func (m *GetProfileRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *GetProfileRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type SetProfileRequest struct {
	AppID  string `protobuf:"bytes,1,opt,name=AppID,proto3" json:"AppID,omitempty"`
	UserID string `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	//
	Address1 string `protobuf:"bytes,3,opt,name=Address1,proto3" json:"Address1,omitempty"`
	Address2 string `protobuf:"bytes,4,opt,name=Address2,proto3" json:"Address2,omitempty"`
	City     string `protobuf:"bytes,5,opt,name=City,proto3" json:"City,omitempty"`
	State    string `protobuf:"bytes,6,opt,name=State,proto3" json:"State,omitempty"`
	Country  string `protobuf:"bytes,7,opt,name=Country,proto3" json:"Country,omitempty"`
	Zip      string `protobuf:"bytes,8,opt,name=Zip,proto3" json:"Zip,omitempty"`
	//
	PhotoURL  string               `protobuf:"bytes,9,opt,name=PhotoURL,proto3" json:"PhotoURL,omitempty"`
	FirstName string               `protobuf:"bytes,10,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName  string               `protobuf:"bytes,11,opt,name=LastName,proto3" json:"LastName,omitempty"`
	BirthDate *timestamp.Timestamp `protobuf:"bytes,12,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	//
	Language string `protobuf:"bytes,13,opt,name=Language,proto3" json:"Language,omitempty"`
	Currency string `protobuf:"bytes,14,opt,name=Currency,proto3" json:"Currency,omitempty"`
	//
	Phone                string   `protobuf:"bytes,15,opt,name=Phone,proto3" json:"Phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetProfileRequest) Reset()         { *m = SetProfileRequest{} }
func (m *SetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*SetProfileRequest) ProtoMessage()    {}
func (*SetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c745b77facf9f532, []int{1}
}

func (m *SetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetProfileRequest.Unmarshal(m, b)
}
func (m *SetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetProfileRequest.Marshal(b, m, deterministic)
}
func (m *SetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetProfileRequest.Merge(m, src)
}
func (m *SetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_SetProfileRequest.Size(m)
}
func (m *SetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetProfileRequest proto.InternalMessageInfo

func (m *SetProfileRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *SetProfileRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SetProfileRequest) GetAddress1() string {
	if m != nil {
		return m.Address1
	}
	return ""
}

func (m *SetProfileRequest) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *SetProfileRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *SetProfileRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *SetProfileRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *SetProfileRequest) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *SetProfileRequest) GetPhotoURL() string {
	if m != nil {
		return m.PhotoURL
	}
	return ""
}

func (m *SetProfileRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *SetProfileRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *SetProfileRequest) GetBirthDate() *timestamp.Timestamp {
	if m != nil {
		return m.BirthDate
	}
	return nil
}

func (m *SetProfileRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *SetProfileRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *SetProfileRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ProfileResponse struct {
	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	//
	Email    string `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=Username,proto3" json:"Username,omitempty"`
	//
	Phone string `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	//
	Address1 string `protobuf:"bytes,5,opt,name=Address1,proto3" json:"Address1,omitempty"`
	Address2 string `protobuf:"bytes,6,opt,name=Address2,proto3" json:"Address2,omitempty"`
	City     string `protobuf:"bytes,7,opt,name=City,proto3" json:"City,omitempty"`
	State    string `protobuf:"bytes,8,opt,name=State,proto3" json:"State,omitempty"`
	Country  string `protobuf:"bytes,9,opt,name=Country,proto3" json:"Country,omitempty"`
	Zip      string `protobuf:"bytes,10,opt,name=Zip,proto3" json:"Zip,omitempty"`
	//
	PhotoURL  string               `protobuf:"bytes,11,opt,name=PhotoURL,proto3" json:"PhotoURL,omitempty"`
	FirstName string               `protobuf:"bytes,12,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName  string               `protobuf:"bytes,13,opt,name=LastName,proto3" json:"LastName,omitempty"`
	BirthDate *timestamp.Timestamp `protobuf:"bytes,14,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	//
	Language             string   `protobuf:"bytes,15,opt,name=Language,proto3" json:"Language,omitempty"`
	Currency             string   `protobuf:"bytes,16,opt,name=Currency,proto3" json:"Currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileResponse) Reset()         { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()    {}
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c745b77facf9f532, []int{2}
}

func (m *ProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileResponse.Unmarshal(m, b)
}
func (m *ProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileResponse.Marshal(b, m, deterministic)
}
func (m *ProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileResponse.Merge(m, src)
}
func (m *ProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileResponse.Size(m)
}
func (m *ProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileResponse proto.InternalMessageInfo

func (m *ProfileResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ProfileResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ProfileResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ProfileResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *ProfileResponse) GetAddress1() string {
	if m != nil {
		return m.Address1
	}
	return ""
}

func (m *ProfileResponse) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *ProfileResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ProfileResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ProfileResponse) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *ProfileResponse) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *ProfileResponse) GetPhotoURL() string {
	if m != nil {
		return m.PhotoURL
	}
	return ""
}

func (m *ProfileResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ProfileResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *ProfileResponse) GetBirthDate() *timestamp.Timestamp {
	if m != nil {
		return m.BirthDate
	}
	return nil
}

func (m *ProfileResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *ProfileResponse) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type ChangePasswordRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	PasswordOld          string   `protobuf:"bytes,2,opt,name=passwordOld,proto3" json:"passwordOld,omitempty"`
	PasswordNew          string   `protobuf:"bytes,3,opt,name=passwordNew,proto3" json:"passwordNew,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c745b77facf9f532, []int{3}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ChangePasswordRequest) GetPasswordOld() string {
	if m != nil {
		return m.PasswordOld
	}
	return ""
}

func (m *ChangePasswordRequest) GetPasswordNew() string {
	if m != nil {
		return m.PasswordNew
	}
	return ""
}

type ChangePasswordResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordResponse) Reset()         { *m = ChangePasswordResponse{} }
func (m *ChangePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordResponse) ProtoMessage()    {}
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c745b77facf9f532, []int{4}
}

func (m *ChangePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordResponse.Unmarshal(m, b)
}
func (m *ChangePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordResponse.Merge(m, src)
}
func (m *ChangePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordResponse.Size(m)
}
func (m *ChangePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordResponse proto.InternalMessageInfo

func (m *ChangePasswordResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetUserSocialIdentitiesRequest struct {
	AppID                string   `protobuf:"bytes,1,opt,name=appID,proto3" json:"appID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserSocialIdentitiesRequest) Reset()         { *m = GetUserSocialIdentitiesRequest{} }
func (m *GetUserSocialIdentitiesRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserSocialIdentitiesRequest) ProtoMessage()    {}
func (*GetUserSocialIdentitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c745b77facf9f532, []int{5}
}

func (m *GetUserSocialIdentitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserSocialIdentitiesRequest.Unmarshal(m, b)
}
func (m *GetUserSocialIdentitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserSocialIdentitiesRequest.Marshal(b, m, deterministic)
}
func (m *GetUserSocialIdentitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserSocialIdentitiesRequest.Merge(m, src)
}
func (m *GetUserSocialIdentitiesRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserSocialIdentitiesRequest.Size(m)
}
func (m *GetUserSocialIdentitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserSocialIdentitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserSocialIdentitiesRequest proto.InternalMessageInfo

func (m *GetUserSocialIdentitiesRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *GetUserSocialIdentitiesRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UserIdentity struct {
	Provider             string   `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ExternalID           string   `protobuf:"bytes,2,opt,name=externalID,proto3" json:"externalID,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserIdentity) Reset()         { *m = UserIdentity{} }
func (m *UserIdentity) String() string { return proto.CompactTextString(m) }
func (*UserIdentity) ProtoMessage()    {}
func (*UserIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_c745b77facf9f532, []int{6}
}

func (m *UserIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserIdentity.Unmarshal(m, b)
}
func (m *UserIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserIdentity.Marshal(b, m, deterministic)
}
func (m *UserIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserIdentity.Merge(m, src)
}
func (m *UserIdentity) XXX_Size() int {
	return xxx_messageInfo_UserIdentity.Size(m)
}
func (m *UserIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_UserIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_UserIdentity proto.InternalMessageInfo

func (m *UserIdentity) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *UserIdentity) GetExternalID() string {
	if m != nil {
		return m.ExternalID
	}
	return ""
}

func (m *UserIdentity) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserIdentity) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserIdentity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserSocialIdentitiesResponse struct {
	Identities           []*UserIdentity `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserSocialIdentitiesResponse) Reset()         { *m = UserSocialIdentitiesResponse{} }
func (m *UserSocialIdentitiesResponse) String() string { return proto.CompactTextString(m) }
func (*UserSocialIdentitiesResponse) ProtoMessage()    {}
func (*UserSocialIdentitiesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c745b77facf9f532, []int{7}
}

func (m *UserSocialIdentitiesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSocialIdentitiesResponse.Unmarshal(m, b)
}
func (m *UserSocialIdentitiesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSocialIdentitiesResponse.Marshal(b, m, deterministic)
}
func (m *UserSocialIdentitiesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSocialIdentitiesResponse.Merge(m, src)
}
func (m *UserSocialIdentitiesResponse) XXX_Size() int {
	return xxx_messageInfo_UserSocialIdentitiesResponse.Size(m)
}
func (m *UserSocialIdentitiesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSocialIdentitiesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserSocialIdentitiesResponse proto.InternalMessageInfo

func (m *UserSocialIdentitiesResponse) GetIdentities() []*UserIdentity {
	if m != nil {
		return m.Identities
	}
	return nil
}

func init() {
	proto.RegisterType((*GetProfileRequest)(nil), "proto.GetProfileRequest")
	proto.RegisterType((*SetProfileRequest)(nil), "proto.SetProfileRequest")
	proto.RegisterType((*ProfileResponse)(nil), "proto.ProfileResponse")
	proto.RegisterType((*ChangePasswordRequest)(nil), "proto.ChangePasswordRequest")
	proto.RegisterType((*ChangePasswordResponse)(nil), "proto.ChangePasswordResponse")
	proto.RegisterType((*GetUserSocialIdentitiesRequest)(nil), "proto.GetUserSocialIdentitiesRequest")
	proto.RegisterType((*UserIdentity)(nil), "proto.UserIdentity")
	proto.RegisterType((*UserSocialIdentitiesResponse)(nil), "proto.UserSocialIdentitiesResponse")
}

func init() {
	proto.RegisterFile("internal/grpc/proto/service.proto", fileDescriptor_c745b77facf9f532)
}

var fileDescriptor_c745b77facf9f532 = []byte{
	// 684 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0xc7, 0x09, 0x21, 0x5f, 0x13, 0x3e, 0x17, 0x48, 0x57, 0x11, 0xa5, 0xa9, 0xab, 0x4a, 0x9c,
	0x12, 0x35, 0x5c, 0x7a, 0x2c, 0x84, 0x16, 0x21, 0xa1, 0x10, 0xc5, 0xe5, 0xc2, 0xcd, 0x24, 0x83,
	0xb3, 0x52, 0x62, 0xbb, 0xbb, 0x6b, 0x68, 0xde, 0xa2, 0x2f, 0xd2, 0xe7, 0xe0, 0xb5, 0xaa, 0xfd,
	0x70, 0x62, 0x43, 0x12, 0xa9, 0xed, 0xc9, 0xfe, 0xcf, 0xcc, 0xce, 0x64, 0xe7, 0x37, 0x9e, 0xc0,
	0x7b, 0x16, 0x48, 0xe4, 0x81, 0x37, 0x6e, 0xf9, 0x3c, 0x1a, 0xb4, 0x22, 0x1e, 0xca, 0xb0, 0x25,
	0x90, 0x3f, 0xb2, 0x01, 0x36, 0xb5, 0x22, 0x05, 0xfd, 0xa8, 0xbf, 0xf3, 0xc3, 0xd0, 0x1f, 0xa3,
	0x09, 0xb9, 0x8f, 0x1f, 0x5a, 0x92, 0x4d, 0x50, 0x48, 0x6f, 0x12, 0x99, 0x38, 0xe7, 0x0c, 0xf6,
	0x2e, 0x51, 0xf6, 0x78, 0xf8, 0xc0, 0xc6, 0xd8, 0xc7, 0x1f, 0x31, 0x0a, 0x49, 0x0e, 0xa0, 0x70,
	0x16, 0x45, 0x57, 0x17, 0x34, 0xd7, 0xc8, 0x9d, 0x54, 0xfa, 0x46, 0x90, 0x1a, 0x14, 0x6f, 0x05,
	0xf2, 0xab, 0x0b, 0xba, 0xae, 0xcd, 0x56, 0x39, 0xbf, 0xf3, 0xb0, 0xe7, 0xfe, 0x5f, 0x0e, 0x52,
	0x87, 0xf2, 0xd9, 0x70, 0xc8, 0x51, 0x88, 0x4f, 0x34, 0xaf, 0x3d, 0x33, 0x9d, 0xf2, 0xb5, 0xe9,
	0x46, 0xc6, 0xd7, 0x26, 0x04, 0x36, 0x3a, 0x4c, 0x4e, 0x69, 0x41, 0xdb, 0xf5, 0xbb, 0xaa, 0xec,
	0x4a, 0x4f, 0x22, 0x2d, 0x9a, 0xca, 0x5a, 0x10, 0x0a, 0xa5, 0x4e, 0x18, 0x07, 0x92, 0x4f, 0x69,
	0x49, 0xdb, 0x13, 0x49, 0x76, 0x21, 0x7f, 0xc7, 0x22, 0x5a, 0xd6, 0x56, 0xf5, 0xaa, 0x2a, 0xf6,
	0x46, 0xa1, 0x0c, 0x6f, 0xfb, 0xd7, 0xb4, 0x62, 0x2a, 0x26, 0x9a, 0x1c, 0x41, 0xe5, 0x1b, 0xe3,
	0x42, 0x76, 0xbd, 0x09, 0x52, 0xd0, 0xce, 0xb9, 0x41, 0x9d, 0xbc, 0xf6, 0xac, 0xb3, 0x6a, 0x4e,
	0x26, 0x9a, 0x7c, 0x86, 0xca, 0x39, 0xe3, 0x72, 0x74, 0xa1, 0x7e, 0xdb, 0x66, 0x23, 0x77, 0x52,
	0x6d, 0xd7, 0x9b, 0x86, 0x4f, 0x33, 0xe1, 0xd3, 0xfc, 0x9e, 0xf0, 0xe9, 0xcf, 0x83, 0x4d, 0xd6,
	0xc0, 0x8f, 0x3d, 0x1f, 0xe9, 0x56, 0x92, 0xd5, 0x68, 0xe5, 0xeb, 0xc4, 0x9c, 0x63, 0x30, 0x98,
	0xd2, 0x6d, 0xe3, 0x4b, 0xb4, 0xea, 0x44, 0x6f, 0x14, 0x06, 0x48, 0x77, 0x4c, 0x27, 0xb4, 0x70,
	0x9e, 0xf3, 0xb0, 0x33, 0x83, 0x25, 0xa2, 0x30, 0x10, 0x98, 0xe2, 0x92, 0xcb, 0x70, 0x39, 0x80,
	0xc2, 0xd7, 0x89, 0xc7, 0xc6, 0x16, 0x97, 0x11, 0xaa, 0xa6, 0xf2, 0x07, 0xea, 0x96, 0x96, 0x56,
	0xa2, 0xe7, 0x35, 0x37, 0x52, 0x35, 0x33, 0x7c, 0x0b, 0x2b, 0xf8, 0x16, 0x97, 0xf0, 0x2d, 0x2d,
	0xe2, 0x5b, 0x5e, 0xc2, 0xb7, 0xb2, 0x90, 0x2f, 0x2c, 0xe6, 0x5b, 0x5d, 0xc5, 0x77, 0x73, 0x15,
	0xdf, 0xad, 0x55, 0x7c, 0xb7, 0xff, 0x95, 0xef, 0xce, 0x0a, 0xbe, 0xbb, 0x59, 0xbe, 0x8e, 0x80,
	0xc3, 0xce, 0xc8, 0x0b, 0x7c, 0xec, 0x79, 0x42, 0x3c, 0x85, 0x7c, 0x98, 0x7c, 0x7c, 0x35, 0x28,
	0xc6, 0x19, 0x9c, 0x46, 0x91, 0x06, 0x54, 0x23, 0x1b, 0x7a, 0x33, 0x1e, 0x5a, 0xa8, 0x69, 0x53,
	0x3a, 0xa2, 0x8b, 0x4f, 0x96, 0x6e, 0xda, 0xe4, 0xb4, 0xa1, 0xf6, 0xb2, 0xa8, 0x1d, 0x22, 0x0a,
	0x25, 0x11, 0x0f, 0x06, 0x28, 0x84, 0x2e, 0x5b, 0xee, 0x27, 0xd2, 0xe9, 0xc2, 0xf1, 0x25, 0x4a,
	0x35, 0x23, 0x6e, 0x38, 0x60, 0xde, 0xf8, 0x6a, 0x88, 0x81, 0x64, 0x92, 0xa1, 0x48, 0xad, 0x0b,
	0x2f, 0xbd, 0x2e, 0xbc, 0x64, 0x5d, 0xc4, 0x99, 0x75, 0x61, 0x94, 0xf3, 0x2b, 0x07, 0x9b, 0x7a,
	0x42, 0x4d, 0x9e, 0xa9, 0xea, 0x52, 0xc4, 0xc3, 0x47, 0x36, 0x44, 0x6e, 0x33, 0xcc, 0x34, 0x39,
	0x06, 0xc0, 0x9f, 0x66, 0x5f, 0xce, 0x12, 0xa5, 0x2c, 0xaa, 0x34, 0xea, 0x19, 0x37, 0x97, 0x35,
	0x42, 0x65, 0x8c, 0x93, 0x19, 0xb7, 0x5b, 0x27, 0xd1, 0x6a, 0x2a, 0xb5, 0xdd, 0x6e, 0x1d, 0xf5,
	0xee, 0xb8, 0x70, 0xb4, 0xf8, 0x7e, 0xb6, 0x39, 0xa7, 0x00, 0x6c, 0x66, 0xa5, 0xb9, 0x46, 0xfe,
	0xa4, 0xda, 0xde, 0x37, 0x73, 0xd1, 0x4c, 0x5f, 0xa5, 0x9f, 0x0a, 0x6b, 0x3f, 0xaf, 0x43, 0xc9,
	0x35, 0x7b, 0x9d, 0x7c, 0x01, 0x98, 0x6f, 0x6a, 0x42, 0xed, 0xd1, 0x57, 0xcb, 0xbb, 0x5e, 0xb3,
	0x9e, 0x17, 0x9f, 0xb8, 0xb3, 0xa6, 0x32, 0xb8, 0xaf, 0x33, 0xb8, 0x7f, 0x91, 0xe1, 0x06, 0xb6,
	0xb3, 0xec, 0xc9, 0x91, 0x8d, 0x5d, 0x38, 0x87, 0xf5, 0xb7, 0x4b, 0xbc, 0xb3, 0x84, 0x3e, 0xbc,
	0x59, 0x32, 0x18, 0xe4, 0xe3, 0xfc, 0x86, 0x2b, 0x06, 0xa7, 0xfe, 0x21, 0xd5, 0xc3, 0x65, 0xcd,
	0x77, 0xd6, 0xce, 0x0f, 0xef, 0xf6, 0x17, 0xfc, 0x69, 0xde, 0x17, 0xf5, 0xe3, 0xf4, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x8c, 0x26, 0x9c, 0x0a, 0x52, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceClient interface {
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	SetProfile(ctx context.Context, in *SetProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
	//
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	//
	GetUserSocialIdentities(ctx context.Context, in *GetUserSocialIdentitiesRequest, opts ...grpc.CallOption) (*UserSocialIdentitiesResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/proto.Service/GetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) SetProfile(ctx context.Context, in *SetProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, "/proto.Service/SetProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, "/proto.Service/ChangePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetUserSocialIdentities(ctx context.Context, in *GetUserSocialIdentitiesRequest, opts ...grpc.CallOption) (*UserSocialIdentitiesResponse, error) {
	out := new(UserSocialIdentitiesResponse)
	err := c.cc.Invoke(ctx, "/proto.Service/GetUserSocialIdentities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
type ServiceServer interface {
	GetProfile(context.Context, *GetProfileRequest) (*ProfileResponse, error)
	SetProfile(context.Context, *SetProfileRequest) (*ProfileResponse, error)
	//
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	//
	GetUserSocialIdentities(context.Context, *GetUserSocialIdentitiesRequest) (*UserSocialIdentitiesResponse, error)
}

// UnimplementedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (*UnimplementedServiceServer) GetProfile(ctx context.Context, req *GetProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (*UnimplementedServiceServer) SetProfile(ctx context.Context, req *SetProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetProfile not implemented")
}
func (*UnimplementedServiceServer) ChangePassword(ctx context.Context, req *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (*UnimplementedServiceServer) GetUserSocialIdentities(ctx context.Context, req *GetUserSocialIdentitiesRequest) (*UserSocialIdentitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserSocialIdentities not implemented")
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Service/GetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_SetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).SetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Service/SetProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).SetProfile(ctx, req.(*SetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Service/ChangePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetUserSocialIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSocialIdentitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetUserSocialIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Service/GetUserSocialIdentities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetUserSocialIdentities(ctx, req.(*GetUserSocialIdentitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _Service_GetProfile_Handler,
		},
		{
			MethodName: "SetProfile",
			Handler:    _Service_SetProfile_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _Service_ChangePassword_Handler,
		},
		{
			MethodName: "GetUserSocialIdentities",
			Handler:    _Service_GetUserSocialIdentities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/proto/service.proto",
}
