// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/handler/proto/service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetProfileRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileRequest) Reset()         { *m = GetProfileRequest{} }
func (m *GetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetProfileRequest) ProtoMessage()    {}
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc27373dff5c1c73, []int{0}
}

func (m *GetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileRequest.Unmarshal(m, b)
}
func (m *GetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileRequest.Merge(m, src)
}
func (m *GetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetProfileRequest.Size(m)
}
func (m *GetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileRequest proto.InternalMessageInfo

func (m *GetProfileRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type SetProfileRequest struct {
	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	//
	Address1 string `protobuf:"bytes,2,opt,name=Address1,proto3" json:"Address1,omitempty"`
	Address2 string `protobuf:"bytes,3,opt,name=Address2,proto3" json:"Address2,omitempty"`
	City     string `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	State    string `protobuf:"bytes,5,opt,name=State,proto3" json:"State,omitempty"`
	Country  string `protobuf:"bytes,6,opt,name=Country,proto3" json:"Country,omitempty"`
	Zip      string `protobuf:"bytes,7,opt,name=Zip,proto3" json:"Zip,omitempty"`
	//
	PhotoURL  string               `protobuf:"bytes,8,opt,name=PhotoURL,proto3" json:"PhotoURL,omitempty"`
	FirstName string               `protobuf:"bytes,9,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName  string               `protobuf:"bytes,10,opt,name=LastName,proto3" json:"LastName,omitempty"`
	BirthDate *timestamp.Timestamp `protobuf:"bytes,11,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	//
	Language             string   `protobuf:"bytes,12,opt,name=Language,proto3" json:"Language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetProfileRequest) Reset()         { *m = SetProfileRequest{} }
func (m *SetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*SetProfileRequest) ProtoMessage()    {}
func (*SetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc27373dff5c1c73, []int{1}
}

func (m *SetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetProfileRequest.Unmarshal(m, b)
}
func (m *SetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetProfileRequest.Marshal(b, m, deterministic)
}
func (m *SetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetProfileRequest.Merge(m, src)
}
func (m *SetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_SetProfileRequest.Size(m)
}
func (m *SetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetProfileRequest proto.InternalMessageInfo

func (m *SetProfileRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SetProfileRequest) GetAddress1() string {
	if m != nil {
		return m.Address1
	}
	return ""
}

func (m *SetProfileRequest) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *SetProfileRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *SetProfileRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *SetProfileRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *SetProfileRequest) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *SetProfileRequest) GetPhotoURL() string {
	if m != nil {
		return m.PhotoURL
	}
	return ""
}

func (m *SetProfileRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *SetProfileRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *SetProfileRequest) GetBirthDate() *timestamp.Timestamp {
	if m != nil {
		return m.BirthDate
	}
	return nil
}

func (m *SetProfileRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type ProfileResponse struct {
	UserID string `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	//
	Address1 string `protobuf:"bytes,2,opt,name=Address1,proto3" json:"Address1,omitempty"`
	Address2 string `protobuf:"bytes,3,opt,name=Address2,proto3" json:"Address2,omitempty"`
	City     string `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	State    string `protobuf:"bytes,5,opt,name=State,proto3" json:"State,omitempty"`
	Country  string `protobuf:"bytes,6,opt,name=Country,proto3" json:"Country,omitempty"`
	Zip      string `protobuf:"bytes,7,opt,name=Zip,proto3" json:"Zip,omitempty"`
	//
	PhotoURL  string               `protobuf:"bytes,8,opt,name=PhotoURL,proto3" json:"PhotoURL,omitempty"`
	FirstName string               `protobuf:"bytes,9,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName  string               `protobuf:"bytes,10,opt,name=LastName,proto3" json:"LastName,omitempty"`
	BirthDate *timestamp.Timestamp `protobuf:"bytes,11,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	//
	Language             string   `protobuf:"bytes,12,opt,name=Language,proto3" json:"Language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileResponse) Reset()         { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()    {}
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc27373dff5c1c73, []int{2}
}

func (m *ProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileResponse.Unmarshal(m, b)
}
func (m *ProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileResponse.Marshal(b, m, deterministic)
}
func (m *ProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileResponse.Merge(m, src)
}
func (m *ProfileResponse) XXX_Size() int {
	return xxx_messageInfo_ProfileResponse.Size(m)
}
func (m *ProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileResponse proto.InternalMessageInfo

func (m *ProfileResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ProfileResponse) GetAddress1() string {
	if m != nil {
		return m.Address1
	}
	return ""
}

func (m *ProfileResponse) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *ProfileResponse) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ProfileResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ProfileResponse) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *ProfileResponse) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

func (m *ProfileResponse) GetPhotoURL() string {
	if m != nil {
		return m.PhotoURL
	}
	return ""
}

func (m *ProfileResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ProfileResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *ProfileResponse) GetBirthDate() *timestamp.Timestamp {
	if m != nil {
		return m.BirthDate
	}
	return nil
}

func (m *ProfileResponse) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func init() {
	proto.RegisterType((*GetProfileRequest)(nil), "proto.GetProfileRequest")
	proto.RegisterType((*SetProfileRequest)(nil), "proto.SetProfileRequest")
	proto.RegisterType((*ProfileResponse)(nil), "proto.ProfileResponse")
}

func init() {
	proto.RegisterFile("internal/handler/proto/service.proto", fileDescriptor_fc27373dff5c1c73)
}

var fileDescriptor_fc27373dff5c1c73 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x53, 0xcb, 0x6a, 0xe3, 0x30,
	0x14, 0x1d, 0xe7, 0xed, 0x9b, 0x81, 0x99, 0x88, 0x21, 0x08, 0x33, 0x30, 0xc1, 0xcc, 0x22, 0x30,
	0x60, 0x33, 0xee, 0xa6, 0xcb, 0xb6, 0x09, 0x2d, 0x85, 0x50, 0x82, 0xdd, 0x6c, 0xba, 0x73, 0x9a,
	0x1b, 0x47, 0xe0, 0x58, 0xae, 0x24, 0x17, 0xf2, 0x11, 0xfd, 0xca, 0xd2, 0xff, 0x28, 0x96, 0xe2,
	0xa4, 0x6d, 0x36, 0x59, 0x74, 0xd9, 0x95, 0x75, 0x1e, 0x3a, 0xd7, 0x1c, 0x71, 0xe1, 0x2f, 0xcb,
	0x14, 0x8a, 0x2c, 0x4e, 0xfd, 0x55, 0x9c, 0x2d, 0x52, 0x14, 0x7e, 0x2e, 0xb8, 0xe2, 0xbe, 0x44,
	0xf1, 0xc8, 0xee, 0xd1, 0xd3, 0x88, 0x34, 0xf5, 0xc7, 0xf9, 0x93, 0x70, 0x9e, 0xa4, 0x68, 0x2c,
	0xf3, 0x62, 0xe9, 0x2b, 0xb6, 0x46, 0xa9, 0xe2, 0x75, 0x6e, 0x7c, 0xee, 0x3f, 0xe8, 0x5d, 0xa1,
	0x9a, 0x0a, 0xbe, 0x64, 0x29, 0x86, 0xf8, 0x50, 0xa0, 0x54, 0xa4, 0x0f, 0xad, 0x99, 0x44, 0x71,
	0x3d, 0xa6, 0xd6, 0xc0, 0x1a, 0xda, 0xe1, 0x16, 0xb9, 0x2f, 0x35, 0xe8, 0x45, 0xc7, 0xba, 0x89,
	0x03, 0x9d, 0xf3, 0xc5, 0x42, 0xa0, 0x94, 0xff, 0x69, 0x4d, 0x2b, 0x3b, 0xfc, 0x46, 0x0b, 0x68,
	0xfd, 0x9d, 0x16, 0x10, 0x02, 0x8d, 0x11, 0x53, 0x1b, 0xda, 0xd0, 0xbc, 0x3e, 0x93, 0x5f, 0xd0,
	0x8c, 0x54, 0xac, 0x90, 0x36, 0x35, 0x69, 0x00, 0xa1, 0xd0, 0x1e, 0xf1, 0x22, 0x53, 0x62, 0x43,
	0x5b, 0x9a, 0xaf, 0x20, 0xf9, 0x09, 0xf5, 0x3b, 0x96, 0xd3, 0xb6, 0x66, 0xcb, 0x63, 0x39, 0x71,
	0xba, 0xe2, 0x8a, 0xcf, 0xc2, 0x09, 0xed, 0x98, 0x89, 0x15, 0x26, 0xbf, 0xc1, 0xbe, 0x64, 0x42,
	0xaa, 0x9b, 0x78, 0x8d, 0xd4, 0xd6, 0xe2, 0x9e, 0x28, 0x6f, 0x4e, 0xe2, 0xad, 0x08, 0xe6, 0x66,
	0x85, 0xc9, 0x29, 0xd8, 0x17, 0x4c, 0xa8, 0xd5, 0xb8, 0xfc, 0xb7, 0xee, 0xc0, 0x1a, 0x76, 0x03,
	0xc7, 0x33, 0x9d, 0x7b, 0x55, 0xe7, 0xde, 0x6d, 0xd5, 0x79, 0xb8, 0x37, 0x9b, 0xd4, 0x2c, 0x29,
	0xe2, 0x04, 0xe9, 0xf7, 0x2a, 0xd5, 0x60, 0xf7, 0xb9, 0x06, 0x3f, 0x76, 0x25, 0xcb, 0x9c, 0x67,
	0x12, 0xbf, 0x5a, 0xfe, 0xec, 0x96, 0x83, 0x27, 0x0b, 0xda, 0x91, 0x59, 0x1a, 0x72, 0x06, 0xb0,
	0x5f, 0x03, 0x42, 0x4d, 0xaa, 0x77, 0xb0, 0x19, 0x4e, 0x7f, 0xab, 0x7c, 0x78, 0x1d, 0xf7, 0x5b,
	0x99, 0x10, 0x1d, 0x26, 0x44, 0xc7, 0x27, 0xcc, 0x5b, 0x5a, 0x38, 0x79, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0x11, 0xfe, 0x03, 0x1a, 0xe1, 0x03, 0x00, 0x00,
}
