// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"

	models "github.com/ProtocolONE/auth1.protocol.one/pkg/models"

	service "github.com/ProtocolONE/auth1.protocol.one/pkg/service"
)

// AuthLogServiceInterface is an autogenerated mock type for the AuthLogServiceInterface type
type AuthLogServiceInterface struct {
	mock.Mock
}

// Add provides a mock function with given fields: reqctx, kind, identity, app, provider
func (_m *AuthLogServiceInterface) Add(reqctx echo.Context, kind service.AuthActionType, identity *models.UserIdentity, app *models.Application, provider *models.AppIdentityProvider) error {
	ret := _m.Called(reqctx, kind, identity, app, provider)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, service.AuthActionType, *models.UserIdentity, *models.Application, *models.AppIdentityProvider) error); ok {
		r0 = rf(reqctx, kind, identity, app, provider)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
