// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/ProtocolONE/auth1.protocol.one/pkg/models"

// AuthLogServiceInterface is an autogenerated mock type for the AuthLogServiceInterface type
type AuthLogServiceInterface struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *AuthLogServiceInterface) Add(_a0 string, _a1 string, _a2 *models.User) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, *models.User) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
