// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CentrifugoServiceInterface is an autogenerated mock type for the CentrifugoServiceInterface type
type CentrifugoServiceInterface struct {
	mock.Mock
}

// Expired provides a mock function with given fields: loginChallenge
func (_m *CentrifugoServiceInterface) Expired(loginChallenge string) error {
	ret := _m.Called(loginChallenge)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(loginChallenge)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InProgress provides a mock function with given fields: loginChallenge
func (_m *CentrifugoServiceInterface) InProgress(loginChallenge string) error {
	ret := _m.Called(loginChallenge)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(loginChallenge)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Success provides a mock function with given fields: loginChallenge, url
func (_m *CentrifugoServiceInterface) Success(loginChallenge string, url string) error {
	ret := _m.Called(loginChallenge, url)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(loginChallenge, url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
