// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/micro/go-micro/client"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/ProtocolONE/geoip-service/pkg/proto"
)

// GeoIp is an autogenerated mock type for the GeoIp type
type GeoIp struct {
	mock.Mock
}

// GetIpData provides a mock function with given fields: ctx, in, opts
func (_m *GeoIp) GetIpData(ctx context.Context, in *proto.GeoIpDataRequest, opts ...client.CallOption) (*proto.GeoIpDataResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.GeoIpDataResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GeoIpDataRequest, ...client.CallOption) *proto.GeoIpDataResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GeoIpDataResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.GeoIpDataRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
