// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import service "github.com/ProtocolONE/auth1.protocol.one/pkg/service"

// LauncherServerService is an autogenerated mock type for the LauncherServerService type
type LauncherServerService struct {
	mock.Mock
}

// InProgress provides a mock function with given fields: loginChallenge
func (_m *LauncherServerService) InProgress(loginChallenge string) {
	_m.Called(loginChallenge)
}

// Register provides a mock function with given fields: c
func (_m *LauncherServerService) Register(c *service.LauncherClient) {
	_m.Called(c)
}

// Success provides a mock function with given fields: loginChallenge, url
func (_m *LauncherServerService) Success(loginChallenge string, url string) {
	_m.Called(loginChallenge, url)
}

// UnRegister provides a mock function with given fields: c
func (_m *LauncherServerService) UnRegister(c *service.LauncherClient) {
	_m.Called(c)
}
