// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MailerInterface is an autogenerated mock type for the MailerInterface type
type MailerInterface struct {
	mock.Mock
}

// Send provides a mock function with given fields: to, subject, body
func (_m *MailerInterface) Send(to string, subject string, body string) error {
	ret := _m.Called(to, subject, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(to, subject, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
