// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mgo "github.com/globalsign/mgo"
import mock "github.com/stretchr/testify/mock"

// MgoSession is an autogenerated mock type for the MgoSession type
type MgoSession struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MgoSession) Close() {
	_m.Called()
}

// Copy provides a mock function with given fields:
func (_m *MgoSession) Copy() *mgo.Session {
	ret := _m.Called()

	var r0 *mgo.Session
	if rf, ok := ret.Get(0).(func() *mgo.Session); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mgo.Session)
		}
	}

	return r0
}

// DB provides a mock function with given fields: name
func (_m *MgoSession) DB(name string) *mgo.Database {
	ret := _m.Called(name)

	var r0 *mgo.Database
	if rf, ok := ret.Get(0).(func(string) *mgo.Database); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mgo.Database)
		}
	}

	return r0
}
