// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import echo "github.com/labstack/echo/v4"
import mock "github.com/stretchr/testify/mock"

// SessionService is an autogenerated mock type for the SessionService type
type SessionService struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *SessionService) Get(_a0 echo.Context, _a1 string) (interface{}, error) {
	ret := _m.Called(_a0, _a1)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(echo.Context, string) interface{}); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(echo.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: _a0, _a1, _a2
func (_m *SessionService) Set(_a0 echo.Context, _a1 string, _a2 interface{}) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, string, interface{}) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
