// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	bson "github.com/globalsign/mgo/bson"
	mock "github.com/stretchr/testify/mock"

	models "github.com/ProtocolONE/auth1.protocol.one/pkg/models"
)

// UserIdentityServiceInterface is an autogenerated mock type for the UserIdentityServiceInterface type
type UserIdentityServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: userIdentity
func (_m *UserIdentityServiceInterface) Create(userIdentity *models.UserIdentity) error {
	ret := _m.Called(userIdentity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.UserIdentity) error); ok {
		r0 = rf(userIdentity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByUser provides a mock function with given fields: ip, userId
func (_m *UserIdentityServiceInterface) FindByUser(ip *models.AppIdentityProvider, userId bson.ObjectId) (*models.UserIdentity, error) {
	ret := _m.Called(ip, userId)

	var r0 *models.UserIdentity
	if rf, ok := ret.Get(0).(func(*models.AppIdentityProvider, bson.ObjectId) *models.UserIdentity); ok {
		r0 = rf(ip, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserIdentity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.AppIdentityProvider, bson.ObjectId) error); ok {
		r1 = rf(ip, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ip, externalID
func (_m *UserIdentityServiceInterface) Get(ip *models.AppIdentityProvider, externalID string) (*models.UserIdentity, error) {
	ret := _m.Called(ip, externalID)

	var r0 *models.UserIdentity
	if rf, ok := ret.Get(0).(func(*models.AppIdentityProvider, string) *models.UserIdentity); ok {
		r0 = rf(ip, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserIdentity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.AppIdentityProvider, string) error); ok {
		r1 = rf(ip, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: userIdentity
func (_m *UserIdentityServiceInterface) Update(userIdentity *models.UserIdentity) error {
	ret := _m.Called(userIdentity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.UserIdentity) error); ok {
		r0 = rf(userIdentity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
