{{- $deployment := .Values.backend -}}
{{- $svcName := printf "%s" .Release.Name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcName }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $deployment.role }}
spec:
  type: {{ $deployment.service.type }}
  ports:
  - name: auth1
    port: {{ $deployment.service.port }}
    targetPort: {{ $deployment.port }}
    protocol: {{ $deployment.service.protocol }}
  - name: auth1-admin
    port: {{ $deployment.adminPort }}
    targetPort: {{ $deployment.adminPort  }}
    protocol: {{ $deployment.service.protocol }}    
  selector:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $deployment.role }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcName }}-grpc
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $deployment.role }}
spec:
  type: {{ $deployment.service.type }}
  ports:
  - name: grpc
    port: {{ $deployment.grpcApiPort }}
    targetPort: {{ $deployment.grpcApiPort  }}
    protocol: {{ $deployment.service.protocol }}
  selector:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $deployment.role }}
